### ISSUE TITLE
Advice - Is the adapter production ready?

### ISSUE THREAD

**Issue by syntonyze** [thumbor-community/redis#2]
Hi guys,
I am looking at using the redis adapter as a result storage in production and I was wondering if you would advise using this in production or if you know anyone that is actively using it.

Some initial testing shows good results, but I noticed the repo has not been updated in years. Is this to do with the stability of the contract with redis API? Is the project still maintained?

Thank you so much for your effort on developing this plugin and for your time in answering my question

**Comment by Bladrak** [comment]
Hello,

To be honest I didn't try the redis storage for anything else than storing smart cropping metadata in production. However it does work.

This repo hosts code that was originally in thumbor, and migrated in here. It is maintained, but doesn't have much activity (probably because there's not much usage). @masom might know a bit more though :)

**Comment by masom** [comment]
Hey @syntonyze,

The repo isn't very active because the redis extension is stable and was in use in production without any issues.

The only negative thing about it is it's a blocking adapter (reads/writes will stop the Tornado IOLoop).

There is a non-blocking experimental redis client at https://github.com/thumbor-community/redis-tornado

**Comment by syntonyze** [comment]
Thank you very much for your feedback guys,
we'll give it a try and let you know.
